version: "3.4"

services:
  php:
    build:
      context: .
      target: symfony_php
      args:
        PHP_VERSION: 8.0
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

volumes:
  php_socket:
