name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: phpstan, phpunit, phpcs

      - name: Run PHPStan
        run: phpstan analyse src

      - name: Run PHPUnit
        run: phpunit

      - name: Run PHPCS
        run: phpcs
